import { Facebook, Instagram, Linkedin, Twitter, Youtube } from "lucide-react";

export const navLinks = [
  {
    id: 1,
    title: "HOME",
    link: "/",
  },
  {
    id: 2,
    title: "GALLERY SHOP",
    link: "/products",
  },
  {
    id: 3,
    title: "CLOTHING",
    link: "/clothing",
  },
  {
    id: 4,
    title: "ABOUT",
    link: "/about",
  },
  {
    id: 5,
    title: "REVIEWS",
    link: "/reviews",
  },
  {
    id: 6,
    title: "CONTACT",
    link: "/contact",
  },
];

export const socioIcons = [
  {
    icon: <Instagram size={35} color="gray" />,
  },
  {
    icon: <Twitter size={35} color="gray" />,
  },
  {
    icon: <Youtube size={35} color="gray" />,
  },
  {
    icon: <Facebook size={35} color="gray" />,
  },
  {
    icon: <Linkedin size={35} color="gray" />,
  },
];

export const responsive = {
  superLargeDesktop: {
    // the naming can be any, depends on you.
    breakpoint: { max: 4000, min: 1024 },
    items: 5,
    slidesToSlide: 2,
  },
  desktop: {
    breakpoint: { max: 1024, min: 800 },
    items: 4,
  },
  tablet: {
    breakpoint: { max: 800, min: 464 },
    items: 2,
  },
  mobile: {
    breakpoint: { max: 464, min: 0 },
    items: 1,
  },
};

export const allProducts = [
  {
    id: 1,
    image: "/images/popImage1.webp",
    desc: "Freedom Family Tree ( Malcom X, MLK and Harriet Tubman)",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 2,
    image: "/images/popImage2.avif",
    desc: "New York Subway",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 3,
    image: "/images/popImage3.webp",
    desc: "THE LAST SUPPER",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 4,
    image: "/images/popImage4.webp",
    desc: "AIR Kobe",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 5,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 6,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 7,
    image: "/images/popImage2.avif",
    desc: "New York Subway",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 8,
    image: "/images/popImage3.webp",
    desc: "THE LAST SUPPER",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 9,
    image: "/images/popImage4.webp",
    desc: "AIR Kobe",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 10,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 11,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 12,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 13,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 14,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 15,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 16,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 17,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 18,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 19,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 20,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 21,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 22,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 23,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 24,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 25,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 26,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 27,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 28,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 29,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 30,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 31,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 32,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 33,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 34,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 35,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 36,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 37,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 38,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 39,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 40,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 41,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 42,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 43,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 44,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 1,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 1,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 1,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 1,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 1,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 1,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 1,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 1,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 1,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 1,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 1,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 1,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 1,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 1,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
  {
    id: 1,
    image: "/images/popImage5.webp",
    desc: "'BLACK IS KING' Beyoncé",
    rating: 4.5,
    price: "$99.9",
  },
];
